pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=test
    actions:
      merge:
        method: merge
        strict: smart+fasttrack
