#!/usr/bin/env bash

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

gcloud --project "$(jq -r .project "$DIR/../platformconfig.json")" iam service-accounts create terraform \
	--description="The user that performs terraform actions" \
	--display-name="terraform"
gcloud projects add-iam-policy-binding "$(jq -r .project "$DIR/../platformconfig.json")" \
	--member="serviceAccount:terraform@$(jq -r .project "$DIR/../platformconfig.json").iam.gserviceaccount.com" \
	--role="roles/owner"
gcloud --project "$(jq -r .project "$DIR/../platformconfig.json")" iam service-accounts keys create "$DIR/../secrets/terraform-credentials.json" \
	--iam-account=terraform@"$(jq -r .project "$DIR/../platformconfig.json")".iam.gserviceaccount.com
