#!/usr/bin/env bash

set -euo pipefail

gcloud --project "bt-lab-walking-skeleton" iam service-accounts create terraform \
	--description="The user that performs terraform actions" \
	--display-name="terraform"
gcloud projects add-iam-policy-binding bt-lab-walking-skeleton \
	--member="serviceAccount:terraform@bt-lab-walking-skeleton.iam.gserviceaccount.com" \
	--role="roles/owner"
gcloud --project "bt-lab-walking-skeleton" iam service-accounts keys create secrets/terraform-credentials.json \
	--iam-account=terraform@bt-lab-walking-skeleton.iam.gserviceaccount.com
