name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - run: brew install shfmt
    - run: brew install hashicorp/tap/terraform
    - run: brew install hashicorp/tap/waypoint
    - run: brew install terragrunt
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy
    - name: Lint
      run: make lint
    - name: Test
      run: make test


  deploy-infrastructure:
    runs-on: ubuntu-latest
    needs:
    - test
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - uses: actions/checkout@v2
    - run: brew install hashicorp/tap/terraform
    - run: brew install terragrunt
    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Deploy Infrastructure
      run: terragrunt apply -auto-approve


  deploy-test:
    runs-on: ubuntu-latest
    needs:
    - deploy-infrastructure
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - uses: actions/checkout@v2
    - run: brew install hashicorp/tap/waypoint
    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - run: gcloud config set run/region "$(jq -r .region platformconfig.json)"
    - run: gcloud auth configure-docker -q
    - name: Deploy
      run: |
        waypoint init
        waypoint up --app=test-web
    - run: |
        ENDPOINT="$(gcloud run services describe --platform managed test-web --format=json | jq -r .status.url)" ./ci/smoketest

  deploy:
    runs-on: ubuntu-latest
    needs:
    - deploy-test
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - uses: actions/checkout@v2
    - run: brew install hashicorp/tap/waypoint
    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - run: gcloud config set run/region "$(jq -r .region platformconfig.json)"
    - run: gcloud auth configure-docker -q
    - name: Deploy
      run: |
        waypoint init
        waypoint up --app=web
    - run: |
        ENDPOINT="$(gcloud run services describe --platform managed web --format=json | jq -r .status.url)" ./ci/smoketest
