name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - run: brew install shfmt
    - run: brew install hashicorp/tap/terraform
    - run: brew install hashicorp/tap/waypoint
    - run: brew install terragrunt
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy
    - name: Lint
      run: make lint
    - name: Test
      run: make test

  deploy:
    runs-on: ubuntu-latest
    needs:
    - test
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - run: brew install hashicorp/tap/terraform
    - run: brew install hashicorp/tap/waypoint
    - run: brew install terragrunt
    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - run: gcloud auth configure-docker -q
    - name: Deploy Infrastructure
      run: terragrunt apply -auto-approve
    - name: Deploy
      run: |
        waypoint init
        waypoint up
    - run: ./ci/smoketest
      env:
        ENDPOINT: https://web-goaisnc5aq-nw.a.run.app
